const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const reveals=document.querySelectorAll('.reveal');
if(reduced){reveals.forEach(el=>el.classList.add('visible'));}else{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12,rootMargin:'0px 0px -30px'});reveals.forEach(el=>observer.observe(el));}

const menu=document.querySelector('.menu'),links=document.querySelector('.links');
menu?.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';});
document.querySelectorAll('.links a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menu?.setAttribute('aria-expanded','false');document.body.style.overflow='';}));

const stepData={de:{capture:{eyebrow:'CANON · DJI · DATEIEN',title:'Medien rein. Ohne Umwege.',text:'USB‑Erkennung für Canon, Datei‑ und Speicherkartenimport für DJI sowie direkte Übergabe an Library Pro.',list:['Canon EDSDK‑Sitzung und Modellanzeige','DJI‑Medien aus Geräten und Speicherkarten','Zentrale Übergabe an Library Pro']},create:{eyebrow:'LOOKS · PRESETS · LIGHTROOM',title:'Bearbeiten. Direkt reagieren.',text:'Ein optimierter Echtzeit‑Editor für Looks, Tonwerte, Details, Zuschnitt und den Lightroom‑Workflow.',list:['Smart Enhance und 14 Studio‑Looks','Eigene Presets speichern und wiederverwenden','Volle Auflösung beim Übernehmen']},deliver:{eyebrow:'PLANUNG · PUBLISHING · INSIGHTS',title:'Fertig machen. Sicher ausliefern.',text:'Ein geführter Ablauf führt Inhalte durch Text, Metadaten, Qualitätscheck und Termin bis zum Planer oder Entwurf.',list:['Sechs klar geführte Arbeitsschritte','Planer, Entwürfe und Instagram‑Werkzeuge','Performance und verfügbare Insights']}},en:{capture:{eyebrow:'CANON · DJI · FILES',title:'Bring media in. No detours.',text:'Canon USB detection, DJI file and card import and direct handoff to Library Pro.',list:['Canon EDSDK session and model display','DJI media from devices and memory cards','Central handoff to Library Pro']},create:{eyebrow:'LOOKS · PRESETS · LIGHTROOM',title:'Edit. See every change.',text:'An optimised real-time editor for looks, tones, details, cropping and the Lightroom workflow.',list:['Smart Enhance and 14 studio looks','Save and reuse custom presets','Full resolution when applying edits']},deliver:{eyebrow:'PLANNING · PUBLISHING · INSIGHTS',title:'Finish. Deliver with confidence.',text:'A guided process takes content through copy, metadata, quality checks and scheduling into the planner or drafts.',list:['Six clearly guided steps','Planner, drafts and Instagram tools','Performance and available insights']}}};
let currentLang=localStorage.getItem('nw-language')==='en'?'en':'de';
let currentStep='capture';
function renderStep(){const d=stepData[currentLang][currentStep];document.querySelector('#stepEyebrow').textContent=d.eyebrow;document.querySelector('#stepTitle').textContent=d.title;document.querySelector('#stepText').textContent=d.text;document.querySelector('#stepList').innerHTML=d.list.map(x=>`<li>${x}</li>`).join('');}
document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{currentStep=button.dataset.step;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b===button));renderStep();}));

const en={home:'NW Visuals',workflow:'Workflow',features:'Features',integrations:'Integrations',roadmap:'Roadmap',store:'App Store info',badge:'MAC APP · VERSION 21.0',hero_title:'Capture.<br><em>Create. Deliver.</em>',hero_text:'One studio for capture, media, editing, planning and publishing — clearly structured and purpose-built for Mac.',discover:'Discover 21.0',availability:'AVAILABILITY',release:'Planned release · Late autumn 2026',only_store:'Later available exclusively through Apple’s App Stores',wf_title:'Three stages.<br><em>One continuous flow.</em>',wf_intro:'Visuals Studio follows the path of your content: capture, create and deliver with confidence.',f_title:'More control.<br><em>Fewer tool changes.</em>',f_intro:'The essential tools stay close together and follow the real creator workflow.',editor_title:'Your look. Instantly visible.',editor_text:'Smart Enhance, cropping, precise tonal controls, 14 built-in looks and custom presets. Full resolution is calculated when applying changes.',library_title:'Your central media layer.',library_text:'Media library, Instagram posts, Create, Smart Studio and drafts come together in one place.',planned:'Ratings, favourites, albums and filters are planned for the next expansion.',account_title:'Sign in. Choose a plan. Start.',account_text:'Register or sign in, then choose Free or Pro. The Pro trial is prepared; StoreKit billing is not yet live.',deliver_title:'All the way to the finished post.',deliver_text:'Media, editing, copy, metadata, quality checks and scheduling are combined in one guided process.',i_title:'Connected to<br><em>your workflow.</em>',i_intro:'Clearly described — without promising functions that are not finished yet.',canon_text:'USB detection, model display and EDSDK session. Direct image transfer is still being expanded.',dji_text:'Import foundation for mounted devices, action cameras, drones and memory cards.',lr_text:'Open an image in Lightroom or Lightroom Classic and bring the export back into the editor.',ig_text:'Planning, publishing and available insights through the configured Meta connection.',r_title:'Included today.<br><em>Planned next.</em>',current:'In the current build',next:'Still in development',c1:'Navigation built around Capture, Create and Deliver',c2:'Capture home and Library Pro foundation',c3:'Real-time editor and six-step Deliver flow',c4:'Account entry, device overview and support',c5:'Canon, DJI, Lightroom and Instagram foundations',n1:'Library Pro ratings, favourites and albums',n2:'Metadata, collections and fast filters',n3:'Production StoreKit billing',n4:'Complete live sync of all studio content',n5:'Extended camera transfer and DJI integration',av_title:'Planned release: Late autumn 2026.',av_text:'The Mac app is the complete studio. iPhone and iPad are planned as mobile companions. There is no public direct download.',planned_for:'PLANNED FOR',footer:'Capture, Create and Deliver for Mac.'};
const de={};document.querySelectorAll('[data-t]').forEach(el=>de[el.dataset.t]=el.textContent);document.querySelectorAll('[data-th]').forEach(el=>de[el.dataset.th]=el.innerHTML);
function setLanguage(lang){currentLang=lang;const dict=lang==='en'?en:de;document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(el=>{if(dict[el.dataset.t])el.textContent=dict[el.dataset.t];});document.querySelectorAll('[data-th]').forEach(el=>{if(dict[el.dataset.th])el.innerHTML=dict[el.dataset.th];});document.querySelectorAll('.lang button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('nw-language',lang);renderStep();}
document.querySelectorAll('.lang button').forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));
setLanguage(currentLang);
